name: MinecraftGPT
main: it.ohalee.minecraftgpt.Main
version: 1.2.6
author: ohAlee
description: A Minecraft plugin that uses ChatGPT
api-version: 1.12.2
commands:
  chatgpt:
    description: A Minecraft plugin that uses ChatGPT
    aliases: [mcgpt, minecraftgpt]